credentials:
  usernames:
    patient_jsmith:
      email: jsmith@email.com
      name: John Smith
      password: 'password123' # You can add more patients here
    patient_skiran:
      email: skiran@email.com
      name: Sonali Kiran
      password: 'mypassword'
cookie:
  expiry_days: 30
  key: random_signature_key_123
  name: glycotwin_cookie
credentials:
  usernames: {}
preauthorized:
  emails: []